# SPDX-License-Identifier: GPL-2.0-only
TECHPACK?=y

ifdef CONFIG_BOARD_CAS
obj-y += stub/ audio/ data/ camera_cas/ video/ display/
header-y += stub/include/uapi/ audio/include/uapi/ camera_cas/include/uapi/
else
ifdef CONFIG_BOARD_PSYCHE
obj-y += stub/ audio_psy/ data/ camera/ video/ display/
header-y += stub/include/uapi/ audio_psy/include/uapi/ camera/include/uapi/
else
obj-y += stub/ audio/ data/ camera/ video/ display/
header-y += stub/include/uapi/ audio/include/uapi/ camera/include/uapi/
endif
endif
